### PR TITLE
use laravel's redirect helper function to redirect the requests

### PR DESCRIPTION
**Pull request by mhemrg**

### CODE REVIEW

**Comment by Saeed-Pooyanfar** [comment]
No!! this lib should works with other frameworks ...

**Comment by mhemrg** [comment]
I think currently we cannot use this package without Laravel. You used Laravel's service provider, env configuration and etc. If you have plan to make it a pure php package, feel free to close the PR.

**Comment by Saeed-Pooyanfar** [comment]
Read README.md again, we can use this lib with other frameworks, checkout my new commits, i used redirect helper if we set last class arg (construct) to true

**Comment by mhemrg** [comment]
Yes, now it's cool :+1:

**Pull request closed without merging**
